#!/bin/sh
#belongs in:
#irods~/iRODS/server/bin/cmd/dmget

#This is on our Archive Resource Server, called by the archive rules
#This is needed to stage data from tape to disk for iRODS to read bit streams
#the $@ is the arguments input from the msiExecCmd called in the rule space separated
#the -a is to update the files last access time on the disk cache in DMF.
#The -q is to queue the request. This prevents serialization of data requests.
echo "$@" | xargs dmget -qa
